on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release and Publish Gem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Build gem
        run: |
          gem build *.gemspec
          echo "::set-output name=gem_file::$(ls *.gem)"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            kitchen-yansible-pusher-*.gem